export const projects = [
  {
    title: 'Sweater Weather',
    image: 'images/placeholders/300x200.png',
    category: 'Backend',
    link:'/s-weather',
    text1: '....',
    text2: '....',
    text3: '....',
    banner: 'images/sw-banner.png',
    pic1: 'images/sw-pic1.png',
    pic2: 'images/sw-pic2.png',
  },
  {
    title: 'Rails Engine',
    image: 'images/placeholders/300x200.png',
    category: 'Backend',
    link: '/r-engine',
    text1: '....',
    text2: '....',
    text3: '....',
    banner: 'images/re-banner.png',
    pic1: 'images/re-pic1.png',
    pic2: 'images/re-pic2.png',
  },
  {
    title: 'Never Alone',
    image: 'images/placeholders/300x200.png',
    category: 'Backend',
    link: '/n-alone',
    text1: '....',
    text2: '....',
    text3: '....',
    banner: 'images/ne-banner.png',
    pic1: 'images/ne-pic1.png',
    pic2: 'images/ne-pic2.png',
  },
]
