export const projects = [
  {
    id: 1,
    title: 'Sweater Weather',
    image: 'images/placeholders/300x200.png',
    category: 'Backend',
    link:'/projects/1',
    text1: '....',
    text2: '....',
    text3: '....',
    banner: '../images/placeholders/1000x400.png',
    pic1: 'images/sw-pic1.png',
    pic2: 'images/sw-pic2.png',
  },
  {
    id: 2,
    title: 'Rails Engine',
    image: '../images/placeholders/300x200.png',
    category: 'Backend',
    link: '/projects/2',
    text1: '....',
    text2: '....',
    text3: '....',
    banner: '../images/placeholders/1000x400.png',
    pic1: 'images/re-pic1.png',
    pic2: 'images/re-pic2.png',
  },
  {
    id: 3,
    title: 'Never Alone',
    image: '../images/placeholders/300x200.png',
    category: 'Backend',
    link: '/projects/3',
    text1: '....',
    text2: '....',
    text3: '....',
    banner: '../images/placeholders/1000x400.png',
    pic1: '../images/ne-pic1.png',
    pic2: 'images/ne-pic2.png',
  },
]
